# Valid Townhalls
INSERT INTO townhall VALUES('validth1','validth1',1,11);
INSERT INTO townhall(townhall_id, username, level) VALUES('validth2','validth2',2);
INSERT INTO townhall(townhall_id, username, level) VALUES('validth3','validth3',3);
INSERT INTO townhall(townhall_id, username, level) VALUES('validth4','validth4',4);
INSERT INTO townhall(townhall_id, username, level) VALUES('validth5','validth5',5);
INSERT INTO townhall(townhall_id, username, level) VALUES('validth6','validth6',6);
INSERT INTO townhall(townhall_id, username, level) VALUES('validth7','validth7',7);
INSERT INTO townhall(townhall_id, username, level) VALUES('validth8','validth8',8);
INSERT INTO townhall(townhall_id, username, level) VALUES('validth9','validth9',9);
INSERT INTO townhall(townhall_id, username, level) VALUES('validth10','validth10',10);
INSERT INTO townhall(townhall_id, username, level) VALUES('validth11','validth11',11);

#Base buildings
INSERT INTO building VALUES('cannon', 'Cannon', 0, 0);
INSERT INTO building VALUES('archtow', 'Archer Tower', 0, 0);
INSERT INTO building VALUES('mortar', 'Mortar', 0, 0);
INSERT INTO building VALUES('air_def', 'Air Defense', 0, 0);
INSERT INTO building VALUES('wiz_tow', 'Wizard Tower', 0, 0);
INSERT INTO building VALUES('air_swpr', 'Air Sweeper', 0, 0);
INSERT INTO building VALUES('tesla', 'Hidden Tesla', 0, 0);
INSERT INTO building VALUES('bomb_tow', 'Bomb Tower', 0, 0);
INSERT INTO building VALUES('x_bow', 'X-Bow', 0, 0);
INSERT INTO building VALUES('infe_tow', 'Inferno Tower', 0, 0);
INSERT INTO building VALUES('eagleart', 'Eagle Artillery', 0, 0);
INSERT INTO building VALUES('walls', 'Walls', 0, 0);
INSERT INTO building VALUES('bomb_trp', 'Bomb', 0, 0);
INSERT INTO building VALUES('sprg_trp', 'Spring Trap', 0, 0);
INSERT INTO building VALUES('airbmb', 'Air Bomb', 0, 0);
INSERT INTO building VALUES('giantbmb', 'Giant Bomb', 0, 0);
INSERT INTO building VALUES('seekmine', 'Seeking Air Mine', 0, 0);
INSERT INTO building VALUES('skl_trap', 'Skeleton Trap', 0, 0);
INSERT INTO building VALUES('gld_mine', 'Gold Mine', 0, 0);
INSERT INTO building VALUES('gld_strg', 'Gold Storage', 0, 0);
INSERT INTO building VALUES('elxr_col', 'Elixir Collector', 0, 0);
INSERT INTO building VALUES('elx_strg', 'Elixir Storage', 0, 0);
INSERT INTO building VALUES('drk_drll', 'Dark Elixir Drill', 0, 0);
INSERT INTO building VALUES('drk_strg', 'Dark Elixir Storage', 0, 0);
INSERT INTO building VALUES('castle', 'Clan Castle', 0, 0);
INSERT INTO building VALUES('armycamp', 'Army Camp', 0, 0);
INSERT INTO building VALUES('king', 'Barbarian King', 0, 0);
INSERT INTO building VALUES('queen', 'Archer Queen', 0, 0);
INSERT INTO building VALUES('warden', 'Grand Warden', 0, 0);

# Valid Buildings
INSERT INTO building VALUES('cannon1', 'Cannon', 100, 1);
INSERT INTO building VALUES('cannon2', 'Cannon', 199.1, 2);
INSERT INTO building VALUES('cannon3', 'Cannon', 297.3, 3);
INSERT INTO building VALUES('cannon4', 'Cannon', 394.6, 4);
INSERT INTO building VALUES('cannon5', 'Cannon', 491, 5);
INSERT INTO building VALUES('cannon6', 'Cannon', 586.5, 6);
INSERT INTO building VALUES('cannon7', 'Cannon', 680.1, 7);
INSERT INTO building VALUES('cannon8', 'Cannon', 771.8, 8);
INSERT INTO building VALUES('cannon9', 'Cannon', 861.6, 9);
INSERT INTO building VALUES('cannon10', 'Cannon', 949.5, 10);
INSERT INTO building VALUES('cannon11', 'Cannon', 969.5, 11);
INSERT INTO building VALUES('cannon12', 'Cannon', 988.6, 12);
INSERT INTO building VALUES('cannon13', 'Cannon', 1006.8, 13);
INSERT INTO building VALUES('cannon14', 'Cannon', 1024.1, 14);
INSERT INTO building VALUES('cannon15', 'Cannon', 1040.5, 15);
INSERT INTO building VALUES('archtow1', 'Archer Tower', 100, 1);
INSERT INTO building VALUES('archtow2', 'Archer Tower', 199.1, 2);
INSERT INTO building VALUES('archtow3', 'Archer Tower', 297.3, 3);
INSERT INTO building VALUES('archtow4', 'Archer Tower', 394.6, 4);
INSERT INTO building VALUES('archtow5', 'Archer Tower', 491, 5);
INSERT INTO building VALUES('archtow6', 'Archer Tower', 586.5, 6);
INSERT INTO building VALUES('archtow7', 'Archer Tower', 681.1, 7);
INSERT INTO building VALUES('archtow8', 'Archer Tower', 774.8, 8);
INSERT INTO building VALUES('archtow9', 'Archer Tower', 867.6, 9);
INSERT INTO building VALUES('archtow10', 'Archer Tower', 959.5, 10);
INSERT INTO building VALUES('archtow11', 'Archer Tower', 984.5, 11);
INSERT INTO building VALUES('archtow12', 'Archer Tower', 1008.6, 12);
INSERT INTO building VALUES('archtow13', 'Archer Tower', 1031.8, 13);
INSERT INTO building VALUES('archtow14', 'Archer Tower', 1053.9, 14);
INSERT INTO building VALUES('archtow15', 'Archer Tower', 1075.1, 15);
INSERT INTO building VALUES('mortar1', 'Mortar', 450, 1);
INSERT INTO building VALUES('mortar2', 'Mortar', 885, 2);
INSERT INTO building VALUES('mortar3', 'Mortar', 1290.1, 3);
INSERT INTO building VALUES('mortar4', 'Mortar', 1665.3, 4);
INSERT INTO building VALUES('mortar5', 'Mortar', 2010.6, 5);
INSERT INTO building VALUES('mortar6', 'Mortar', 2326, 6);
INSERT INTO building VALUES('mortar7', 'Mortar', 2611.5, 7);
INSERT INTO building VALUES('mortar8', 'Mortar', 2867.1, 8);
INSERT INTO building VALUES('mortar9', 'Mortar', 3092.8, 9);
INSERT INTO building VALUES('mortar10', 'Mortar', 3288.6, 10);
INSERT INTO building VALUES('air_def1', 'Air Defense', 50, 1);
INSERT INTO building VALUES('air_def2', 'Air Defense', 99.1, 2);
INSERT INTO building VALUES('air_def3', 'Air Defense', 147.3, 3);
INSERT INTO building VALUES('air_def4', 'Air Defense', 194.6, 4);
INSERT INTO building VALUES('air_def5', 'Air Defense', 241, 5);
INSERT INTO building VALUES('air_def6', 'Air Defense', 286.5, 6);
INSERT INTO building VALUES('air_def7', 'Air Defense', 331.1, 7);
INSERT INTO building VALUES('air_def8', 'Air Defense', 374.8, 8);
INSERT INTO building VALUES('air_def9', 'Air Defense', 417.6, 9);
INSERT INTO building VALUES('wiz_tow1', 'Wizard Tower', 450, 1);
INSERT INTO building VALUES('wiz_tow2', 'Wizard Tower', 870.1, 2);
INSERT INTO building VALUES('wiz_tow3', 'Wizard Tower', 1260.3, 3);
INSERT INTO building VALUES('wiz_tow4', 'Wizard Tower', 1550.4, 4);
INSERT INTO building VALUES('wiz_tow5', 'Wizard Tower', 1840.6, 5);
INSERT INTO building VALUES('wiz_tow6', 'Wizard Tower', 2130.9, 6);
INSERT INTO building VALUES('wiz_tow7', 'Wizard Tower', 2321, 7);
INSERT INTO building VALUES('wiz_tow8', 'Wizard Tower', 2511.2, 8);
INSERT INTO building VALUES('wiz_tow9', 'Wizard Tower', 2701.5, 9);
INSERT INTO building VALUES('wiz_tow10', 'Wizard Tower', 2891.9, 10);
INSERT INTO building VALUES('air_swpr1', 'Air Sweeper', 20, 1);
INSERT INTO building VALUES('air_swpr2', 'Air Sweeper', 39.1, 2);
INSERT INTO building VALUES('air_swpr3', 'Air Sweeper', 57.3, 3);
INSERT INTO building VALUES('air_swpr4', 'Air Sweeper', 74.6, 4);
INSERT INTO building VALUES('air_swpr5', 'Air Sweeper', 91, 5);
INSERT INTO building VALUES('air_swpr6', 'Air Sweeper', 106.5, 6);
INSERT INTO building VALUES('tesla1', 'Hidden Tesla', 100, 1);
INSERT INTO building VALUES('tesla2', 'Hidden Tesla', 199.1, 2);
INSERT INTO building VALUES('tesla3', 'Hidden Tesla', 297.3, 3);
INSERT INTO building VALUES('tesla4', 'Hidden Tesla', 394.6, 4);
INSERT INTO building VALUES('tesla5', 'Hidden Tesla', 491, 5);
INSERT INTO building VALUES('tesla6', 'Hidden Tesla', 586.5, 6);
INSERT INTO building VALUES('tesla7', 'Hidden Tesla', 681.1, 7);
INSERT INTO building VALUES('tesla8', 'Hidden Tesla', 774.8, 8);
INSERT INTO building VALUES('tesla9', 'Hidden Tesla', 867.6, 9);
INSERT INTO building VALUES('bomb_tow1', 'Bomb Tower', 400, 1);
INSERT INTO building VALUES('bomb_tow2', 'Bomb Tower', 820.1, 2);
INSERT INTO building VALUES('bomb_tow3', 'Bomb Tower', 1260.3, 3);
INSERT INTO building VALUES('bomb_tow4', 'Bomb Tower', 1720.6, 4);
INSERT INTO building VALUES('bomb_tow5', 'Bomb Tower', 2201, 5);
INSERT INTO building VALUES('x_bow1', 'X-Bow', 900, 1);
INSERT INTO building VALUES('x_bow2', 'X-Bow', 1300, 2);
INSERT INTO building VALUES('x_bow3', 'X-Bow', 1500, 3);
INSERT INTO building VALUES('x_bow4', 'X-Bow', 1600, 4);
INSERT INTO building VALUES('x_bow5', 'X-Bow', 1897.3, 5);
INSERT INTO building VALUES('infe_tow1', 'Inferno Tower', 2950, 1);
INSERT INTO building VALUES('infe_tow2', 'Inferno Tower', 3250, 2);
INSERT INTO building VALUES('infe_tow3', 'Inferno Tower', 3549.1, 3);
INSERT INTO building VALUES('infe_tow4', 'Inferno Tower', 3847.3, 4);
INSERT INTO building VALUES('infe_tow5', 'Inferno Tower', 5144.6, 5);
INSERT INTO building VALUES('eagleart1', 'Eagle Artillery', 5200, 1);
INSERT INTO building VALUES('eagleart2', 'Eagle Artillery', 10200.1, 2);
INSERT INTO building VALUES('walls1', 'Walls', 8, 1);
INSERT INTO building VALUES('walls2', 'Walls', 16, 2);
INSERT INTO building VALUES('walls3', 'Walls', 20, 3);
INSERT INTO building VALUES('walls4', 'Walls', 22.7, 4);
INSERT INTO building VALUES('walls5', 'Walls', 24.7, 5);
INSERT INTO building VALUES('walls6', 'Walls', 26.3, 6);
INSERT INTO building VALUES('walls7', 'Walls', 27.4, 7);
INSERT INTO building VALUES('walls8', 'Walls', 28.3, 8);
INSERT INTO building VALUES('walls9', 'Walls', 29.1, 9);
INSERT INTO building VALUES('walls10', 'Walls', 29.8, 10);
INSERT INTO building VALUES('walls11', 'Walls', 30.5, 11);
INSERT INTO building VALUES('walls12', 'Walls', 33.2, 12);
INSERT INTO building VALUES('bomb_trp1', 'Bomb', 25, 1);
INSERT INTO building VALUES('bomb_trp2', 'Bomb', 49.1, 2);
INSERT INTO building VALUES('bomb_trp3', 'Bomb', 72.3, 3);
INSERT INTO building VALUES('bomb_trp4', 'Bomb', 94.6, 4);
INSERT INTO building VALUES('bomb_trp5', 'Bomb', 116, 5);
INSERT INTO building VALUES('bomb_trp6', 'Bomb', 136.5, 6);
INSERT INTO building VALUES('sprg_trp1', 'Spring Trap', 25, 1);
INSERT INTO building VALUES('sprg_trp2', 'Spring Trap', 51.1, 2);
INSERT INTO building VALUES('sprg_trp3', 'Spring Trap', 78.3, 3);
INSERT INTO building VALUES('sprg_trp4', 'Spring Trap', 106.6, 4);
INSERT INTO building VALUES('sprg_trp5', 'Spring Trap', 136, 5);
INSERT INTO building VALUES('airbmb1', 'Air Bomb', 100, 1);
INSERT INTO building VALUES('airbmb2', 'Air Bomb', 199.1, 2);
INSERT INTO building VALUES('airbmb3', 'Air Bomb', 297.3, 3);
INSERT INTO building VALUES('airbmb4', 'Air Bomb', 394.6, 4);
INSERT INTO building VALUES('giantbmb1', 'Giant Bomb', 150, 1);
INSERT INTO building VALUES('giantbmb2', 'Giant Bomb', 299.1, 2);
INSERT INTO building VALUES('giantbmb3', 'Giant Bomb', 447.3, 3);
INSERT INTO building VALUES('giantbmb4', 'Giant Bomb', 594.6, 4);
INSERT INTO building VALUES('seekmine1', 'Seeking Air Mine', 150, 1);
INSERT INTO building VALUES('seekmine2', 'Seeking Air Mine', 299.1, 2);
INSERT INTO building VALUES('seekmine3', 'Seeking Air Mine', 447.3, 3);
INSERT INTO building VALUES('skl_trap1', 'Skelton Trap', 80, 1);
INSERT INTO building VALUES('skl_trap2', 'Skelton Trap', 159.1, 2);
INSERT INTO building VALUES('skl_trap3', 'Skelton Trap', 237.3, 3);
INSERT INTO building VALUES('gld_mine1', 'Gold Mine', 80, 1);
INSERT INTO building VALUES('gld_mine2', 'Gold Mine', 150, 2);
INSERT INTO building VALUES('gld_mine3', 'Gold Mine', 210, 3);
INSERT INTO building VALUES('gld_mine4', 'Gold Mine', 260, 4);
INSERT INTO building VALUES('gld_mine5', 'Gold Mine', 300, 5);
INSERT INTO building VALUES('gld_mine6', 'Gold Mine', 340.1, 6);
INSERT INTO building VALUES('gld_mine7', 'Gold Mine', 380.3, 7);
INSERT INTO building VALUES('gld_mine8', 'Gold Mine', 420.6, 8);
INSERT INTO building VALUES('gld_mine9', 'Gold Mine', 461, 9);
INSERT INTO building VALUES('gld_mine10', 'Gold Mine', 501.5, 10);
INSERT INTO building VALUES('gld_mine11', 'Gold Mine', 542.1, 11);
INSERT INTO building VALUES('gld_mine12', 'Gold Mine', 582.8, 12);
INSERT INTO building VALUES('gld_strg1', 'Gold Storage', 80, 1);
INSERT INTO building VALUES('gld_strg2', 'Gold Storage', 159.1, 2);
INSERT INTO building VALUES('gld_strg3', 'Gold Storage', 237.3, 3);
INSERT INTO building VALUES('gld_strg4', 'Gold Storage', 315.5, 4);
INSERT INTO building VALUES('gld_strg5', 'Gold Storage', 393.7, 5);
INSERT INTO building VALUES('gld_strg6', 'Gold Storage', 471.9, 6);
INSERT INTO building VALUES('gld_strg7', 'Gold Storage', 550.1, 7);
INSERT INTO building VALUES('gld_strg8', 'Gold Storage', 628.3, 8);
INSERT INTO building VALUES('gld_strg9', 'Gold Storage', 706.5, 9);
INSERT INTO building VALUES('gld_strg10', 'Gold Storage', 784.7, 10);
INSERT INTO building VALUES('gld_strg11', 'Gold Storage', 862.9, 11);
INSERT INTO building VALUES('gld_strg12', 'Gold Storage', 941.1, 12);
INSERT INTO building VALUES('elxr_col1', 'Elixir Collector', 80, 1);
INSERT INTO building VALUES('elxr_col2', 'Elixir Collector', 150, 2);
INSERT INTO building VALUES('elxr_col3', 'Elixir Collector', 210, 3);
INSERT INTO building VALUES('elxr_col4', 'Elixir Collector', 260, 4);
INSERT INTO building VALUES('elxr_col5', 'Elixir Collector', 300, 5);
INSERT INTO building VALUES('elxr_col6', 'Elixir Collector', 340.1, 6);
INSERT INTO building VALUES('elxr_col7', 'Elixir Collector', 380.3, 7);
INSERT INTO building VALUES('elxr_col8', 'Elixir Collector', 420.6, 8);
INSERT INTO building VALUES('elxr_col9', 'Elixir Collector', 461, 9);
INSERT INTO building VALUES('elxr_col10', 'Elixir Collector', 501.5, 10);
INSERT INTO building VALUES('elxr_col11', 'Elixir Collector', 542.1, 11);
INSERT INTO building VALUES('elxr_col12', 'Elixir Collector', 582.8, 12);
INSERT INTO building VALUES('elx_strg1', 'Elixir Storage', 80, 1);
INSERT INTO building VALUES('elx_strg2', 'Elixir Storage', 159.1, 2);
INSERT INTO building VALUES('elx_strg3', 'Elixir Storage', 237.3, 3);
INSERT INTO building VALUES('elx_strg4', 'Elixir Storage', 315.5, 4);
INSERT INTO building VALUES('elx_strg5', 'Elixir Storage', 393.7, 5);
INSERT INTO building VALUES('elx_strg6', 'Elixir Storage', 471.9, 6);
INSERT INTO building VALUES('elx_strg7', 'Elixir Storage', 550.1, 7);
INSERT INTO building VALUES('elx_strg8', 'Elixir Storage', 628.3, 8);
INSERT INTO building VALUES('elx_strg9', 'Elixir Storage', 706.5, 9);
INSERT INTO building VALUES('elx_strg10', 'Elixir Storage', 784.7, 10);
INSERT INTO building VALUES('elx_strg11', 'Elixir Storage', 862.9, 11);
INSERT INTO building VALUES('elx_strg12', 'Elixir Storage', 941.1, 12);
INSERT INTO building VALUES('drk_drll1', 'Dark Elixir Drill', 80, 1);
INSERT INTO building VALUES('drk_drll2', 'Dark Elixir Drill', 159.1, 2);
INSERT INTO building VALUES('drk_drll3', 'Dark Elixir Drill', 237.3, 3);
INSERT INTO building VALUES('drk_drll4', 'Dark Elixir Drill', 315.5, 4);
INSERT INTO building VALUES('drk_drll5', 'Dark Elixir Drill', 393.7, 5);
INSERT INTO building VALUES('drk_drll6', 'Dark Elixir Drill', 471.9, 6);
INSERT INTO building VALUES('drk_strg1', 'Dark Elixir Storage', 80, 1);
INSERT INTO building VALUES('drk_strg2', 'Dark Elixir Storage', 159.1, 2);
INSERT INTO building VALUES('drk_strg3', 'Dark Elixir Storage', 237.3, 3);
INSERT INTO building VALUES('drk_strg4', 'Dark Elixir Storage', 315.5, 4);
INSERT INTO building VALUES('drk_strg5', 'Dark Elixir Storage', 393.7, 5);
INSERT INTO building VALUES('drk_strg6', 'Dark Elixir Storage', 471.9, 6);
INSERT INTO building VALUES('king_off1', 'Barbarian King-off', 40, 1);
INSERT INTO building VALUES('king_off2', 'Barbarian King-off', 80, 2);
INSERT INTO building VALUES('king_off3', 'Barbarian King-off', 120, 3);
INSERT INTO building VALUES('king_off4', 'Barbarian King-off', 160, 4);
INSERT INTO building VALUES('king_off5', 'Barbarian King-off', 200, 5);
INSERT INTO building VALUES('king_off6', 'Barbarian King-off', 240, 6);
INSERT INTO building VALUES('king_off7', 'Barbarian King-off', 280, 7);
INSERT INTO building VALUES('king_off8', 'Barbarian King-off', 320, 8);
INSERT INTO building VALUES('king_off9', 'Barbarian King-off', 360, 9);
INSERT INTO building VALUES('king_off10', 'Barbarian King-off', 400, 10);
INSERT INTO building VALUES('king_off11', 'Barbarian King-off', 440, 11);
INSERT INTO building VALUES('king_off12', 'Barbarian King-off', 480, 12);
INSERT INTO building VALUES('king_off13', 'Barbarian King-off', 520, 13);
INSERT INTO building VALUES('king_off14', 'Barbarian King-off', 560, 14);
INSERT INTO building VALUES('king_off15', 'Barbarian King-off', 600, 15);
INSERT INTO building VALUES('king_off16', 'Barbarian King-off', 640, 16);
INSERT INTO building VALUES('king_off17', 'Barbarian King-off', 680, 17);
INSERT INTO building VALUES('king_off18', 'Barbarian King-off', 720, 18);
INSERT INTO building VALUES('king_off19', 'Barbarian King-off', 760, 19);
INSERT INTO building VALUES('king_off20', 'Barbarian King-off', 780, 20);
INSERT INTO building VALUES('king_off21', 'Barbarian King-off', 800, 21);
INSERT INTO building VALUES('king_off22', 'Barbarian King-off', 820, 22);
INSERT INTO building VALUES('king_off23', 'Barbarian King-off', 840, 23);
INSERT INTO building VALUES('king_off24', 'Barbarian King-off', 860, 24);
INSERT INTO building VALUES('king_off25', 'Barbarian King-off', 880, 25);
INSERT INTO building VALUES('king_off26', 'Barbarian King-off', 900, 26);
INSERT INTO building VALUES('king_off27', 'Barbarian King-off', 920, 27);
INSERT INTO building VALUES('king_off28', 'Barbarian King-off', 940, 28);
INSERT INTO building VALUES('king_off29', 'Barbarian King-off', 960, 29);
INSERT INTO building VALUES('king_off30', 'Barbarian King-off', 980, 30);
INSERT INTO building VALUES('king_off31', 'Barbarian King-off', 1000, 31);
INSERT INTO building VALUES('king_off32', 'Barbarian King-off', 1020, 32);
INSERT INTO building VALUES('king_off33', 'Barbarian King-off', 1040, 33);
INSERT INTO building VALUES('king_off34', 'Barbarian King-off', 1060, 34);
INSERT INTO building VALUES('king_off35', 'Barbarian King-off', 1080, 35);
INSERT INTO building VALUES('king_off36', 'Barbarian King-off', 1100, 36);
INSERT INTO building VALUES('king_off37', 'Barbarian King-off', 1120, 37);
INSERT INTO building VALUES('king_off38', 'Barbarian King-off', 1140, 38);
INSERT INTO building VALUES('king_off39', 'Barbarian King-off', 1160, 39);
INSERT INTO building VALUES('king_off40', 'Barbarian King-off', 1180, 40);
INSERT INTO building VALUES('king_off41', 'Barbarian King-off', 1200, 41);
INSERT INTO building VALUES('king_off42', 'Barbarian King-off', 1220, 42);
INSERT INTO building VALUES('king_off43', 'Barbarian King-off', 1240, 43);
INSERT INTO building VALUES('king_off44', 'Barbarian King-off', 1260, 44);
INSERT INTO building VALUES('king_off45', 'Barbarian King-off', 1280, 45);
INSERT INTO building VALUES('king_def1', 'Barbarian King-def', 20, 1);
INSERT INTO building VALUES('king_def2', 'Barbarian King-def', 39, 2);
INSERT INTO building VALUES('king_def3', 'Barbarian King-def', 57.9, 3);
INSERT INTO building VALUES('king_def4', 'Barbarian King-def', 76.7, 4);
INSERT INTO building VALUES('king_def5', 'Barbarian King-def', 95.4, 5);
INSERT INTO building VALUES('king_def6', 'Barbarian King-def', 114, 6);
INSERT INTO building VALUES('king_def7', 'Barbarian King-def', 132.5, 7);
INSERT INTO building VALUES('king_def8', 'Barbarian King-def', 150.9, 8);
INSERT INTO building VALUES('king_def9', 'Barbarian King-def', 169.2, 9);
INSERT INTO building VALUES('king_def10', 'Barbarian King-def', 187.4, 10);
INSERT INTO building VALUES('king_def11', 'Barbarian King-def', 205.5, 11);
INSERT INTO building VALUES('king_def12', 'Barbarian King-def', 223.5, 12);
INSERT INTO building VALUES('king_def13', 'Barbarian King-def', 241.4, 13);
INSERT INTO building VALUES('king_def14', 'Barbarian King-def', 259.2, 14);
INSERT INTO building VALUES('king_def15', 'Barbarian King-def', 276.9, 15);
INSERT INTO building VALUES('king_def16', 'Barbarian King-def', 294.5, 16);
INSERT INTO building VALUES('king_def17', 'Barbarian King-def', 312, 17);
INSERT INTO building VALUES('king_def18', 'Barbarian King-def', 329.4, 18);
INSERT INTO building VALUES('king_def19', 'Barbarian King-def', 346.7, 19);
INSERT INTO building VALUES('king_def20', 'Barbarian King-def', 363.9, 20);
INSERT INTO building VALUES('king_def21', 'Barbarian King-def', 381, 21);
INSERT INTO building VALUES('king_def22', 'Barbarian King-def', 398, 22);
INSERT INTO building VALUES('king_def23', 'Barbarian King-def', 414.9, 23);
INSERT INTO building VALUES('king_def24', 'Barbarian King-def', 431.7, 24);
INSERT INTO building VALUES('king_def25', 'Barbarian King-def', 448.4, 25);
INSERT INTO building VALUES('king_def26', 'Barbarian King-def', 465, 26);
INSERT INTO building VALUES('king_def27', 'Barbarian King-def', 481.5, 27);
INSERT INTO building VALUES('king_def28', 'Barbarian King-def', 497.9, 28);
INSERT INTO building VALUES('king_def29', 'Barbarian King-def', 514.2, 29);
INSERT INTO building VALUES('king_def30', 'Barbarian King-def', 530.4, 30);
INSERT INTO building VALUES('king_def31', 'Barbarian King-def', 546.499999999999, 31);
INSERT INTO building VALUES('king_def32', 'Barbarian King-def', 562.499999999999, 32);
INSERT INTO building VALUES('king_def33', 'Barbarian King-def', 578.399999999999, 33);
INSERT INTO building VALUES('king_def34', 'Barbarian King-def', 594.199999999999, 34);
INSERT INTO building VALUES('king_def35', 'Barbarian King-def', 609.899999999999, 35);
INSERT INTO building VALUES('king_def36', 'Barbarian King-def', 625.499999999999, 36);
INSERT INTO building VALUES('king_def37', 'Barbarian King-def', 640.999999999999, 37);
INSERT INTO building VALUES('king_def38', 'Barbarian King-def', 656.399999999999, 38);
INSERT INTO building VALUES('king_def39', 'Barbarian King-def', 671.699999999999, 39);
INSERT INTO building VALUES('king_def40', 'Barbarian King-def', 686.899999999999, 40);
INSERT INTO building VALUES('king_def41', 'Barbarian King-def', 701.999999999999, 41);
INSERT INTO building VALUES('king_def42', 'Barbarian King-def', 716.999999999999, 42);
INSERT INTO building VALUES('king_def43', 'Barbarian King-def', 731.899999999999, 43);
INSERT INTO building VALUES('king_def44', 'Barbarian King-def', 746.699999999999, 44);
INSERT INTO building VALUES('king_def45', 'Barbarian King-def', 761.4, 45);
INSERT INTO building VALUES('qeen_off1', 'Archer Queen-off', 50, 1);
INSERT INTO building VALUES('qeen_off2', 'Archer Queen-off', 100, 2);
INSERT INTO building VALUES('qeen_off3', 'Archer Queen-off', 150, 3);
INSERT INTO building VALUES('qeen_off4', 'Archer Queen-off', 200, 4);
INSERT INTO building VALUES('qeen_off5', 'Archer Queen-off', 250, 5);
INSERT INTO building VALUES('qeen_off6', 'Archer Queen-off', 300, 6);
INSERT INTO building VALUES('qeen_off7', 'Archer Queen-off', 350, 7);
INSERT INTO building VALUES('qeen_off8', 'Archer Queen-off', 400, 8);
INSERT INTO building VALUES('qeen_off9', 'Archer Queen-off', 450, 9);
INSERT INTO building VALUES('qeen_off10', 'Archer Queen-off', 500, 10);
INSERT INTO building VALUES('qeen_off11', 'Archer Queen-off', 550, 11);
INSERT INTO building VALUES('qeen_off12', 'Archer Queen-off', 600, 12);
INSERT INTO building VALUES('qeen_off13', 'Archer Queen-off', 650, 13);
INSERT INTO building VALUES('qeen_off14', 'Archer Queen-off', 700, 14);
INSERT INTO building VALUES('qeen_off15', 'Archer Queen-off', 750, 15);
INSERT INTO building VALUES('qeen_off16', 'Archer Queen-off', 800, 16);
INSERT INTO building VALUES('qeen_off17', 'Archer Queen-off', 850, 17);
INSERT INTO building VALUES('qeen_off18', 'Archer Queen-off', 900, 18);
INSERT INTO building VALUES('qeen_off19', 'Archer Queen-off', 950, 19);
INSERT INTO building VALUES('qeen_off20', 'Archer Queen-off', 985, 20);
INSERT INTO building VALUES('qeen_off21', 'Archer Queen-off', 1020, 21);
INSERT INTO building VALUES('qeen_off22', 'Archer Queen-off', 1055, 22);
INSERT INTO building VALUES('qeen_off23', 'Archer Queen-off', 1090, 23);
INSERT INTO building VALUES('qeen_off24', 'Archer Queen-off', 1125, 24);
INSERT INTO building VALUES('qeen_off25', 'Archer Queen-off', 1160, 25);
INSERT INTO building VALUES('qeen_off26', 'Archer Queen-off', 1195, 26);
INSERT INTO building VALUES('qeen_off27', 'Archer Queen-off', 1230, 27);
INSERT INTO building VALUES('qeen_off28', 'Archer Queen-off', 1265, 28);
INSERT INTO building VALUES('qeen_off29', 'Archer Queen-off', 1300, 29);
INSERT INTO building VALUES('qeen_off30', 'Archer Queen-off', 1335, 30);
INSERT INTO building VALUES('qeen_off31', 'Archer Queen-off', 1370, 31);
INSERT INTO building VALUES('qeen_off32', 'Archer Queen-off', 1405, 32);
INSERT INTO building VALUES('qeen_off33', 'Archer Queen-off', 1440, 33);
INSERT INTO building VALUES('qeen_off34', 'Archer Queen-off', 1475, 34);
INSERT INTO building VALUES('qeen_off35', 'Archer Queen-off', 1510, 35);
INSERT INTO building VALUES('qeen_off36', 'Archer Queen-off', 1545, 36);
INSERT INTO building VALUES('qeen_off37', 'Archer Queen-off', 1580, 37);
INSERT INTO building VALUES('qeen_off38', 'Archer Queen-off', 1615, 38);
INSERT INTO building VALUES('qeen_off39', 'Archer Queen-off', 1650, 39);
INSERT INTO building VALUES('qeen_off40', 'Archer Queen-off', 1685, 40);
INSERT INTO building VALUES('qeen_off41', 'Archer Queen-off', 1720, 41);
INSERT INTO building VALUES('qeen_off42', 'Archer Queen-off', 1755, 42);
INSERT INTO building VALUES('qeen_off43', 'Archer Queen-off', 1790, 43);
INSERT INTO building VALUES('qeen_off44', 'Archer Queen-off', 1825, 44);
INSERT INTO building VALUES('qeen_off45', 'Archer Queen-off', 1860, 45);
INSERT INTO building VALUES('qeen_def1', 'Archer Queen-def', 44, 1);
INSERT INTO building VALUES('qeen_def2', 'Archer Queen-def', 87, 2);
INSERT INTO building VALUES('qeen_def3', 'Archer Queen-def', 129.9, 3);
INSERT INTO building VALUES('qeen_def4', 'Archer Queen-def', 172.7, 4);
INSERT INTO building VALUES('qeen_def5', 'Archer Queen-def', 215.4, 5);
INSERT INTO building VALUES('qeen_def6', 'Archer Queen-def', 258, 6);
INSERT INTO building VALUES('qeen_def7', 'Archer Queen-def', 300.5, 7);
INSERT INTO building VALUES('qeen_def8', 'Archer Queen-def', 342.9, 8);
INSERT INTO building VALUES('qeen_def9', 'Archer Queen-def', 385.2, 9);
INSERT INTO building VALUES('qeen_def10', 'Archer Queen-def', 427.4, 10);
INSERT INTO building VALUES('qeen_def11', 'Archer Queen-def', 469.5, 11);
INSERT INTO building VALUES('qeen_def12', 'Archer Queen-def', 511.5, 12);
INSERT INTO building VALUES('qeen_def13', 'Archer Queen-def', 553.4, 13);
INSERT INTO building VALUES('qeen_def14', 'Archer Queen-def', 595.2, 14);
INSERT INTO building VALUES('qeen_def15', 'Archer Queen-def', 636.9, 15);
INSERT INTO building VALUES('qeen_def16', 'Archer Queen-def', 678.5, 16);
INSERT INTO building VALUES('qeen_def17', 'Archer Queen-def', 720, 17);
INSERT INTO building VALUES('qeen_def18', 'Archer Queen-def', 761.4, 18);
INSERT INTO building VALUES('qeen_def19', 'Archer Queen-def', 802.7, 19);
INSERT INTO building VALUES('qeen_def20', 'Archer Queen-def', 843.9, 20);
INSERT INTO building VALUES('qeen_def21', 'Archer Queen-def', 885, 21);
INSERT INTO building VALUES('qeen_def22', 'Archer Queen-def', 926, 22);
INSERT INTO building VALUES('qeen_def23', 'Archer Queen-def', 966.9, 23);
INSERT INTO building VALUES('qeen_def24', 'Archer Queen-def', 1007.7, 24);
INSERT INTO building VALUES('qeen_def25', 'Archer Queen-def', 1048.4, 25);
INSERT INTO building VALUES('qeen_def26', 'Archer Queen-def', 1089, 26);
INSERT INTO building VALUES('qeen_def27', 'Archer Queen-def', 1129.5, 27);
INSERT INTO building VALUES('qeen_def28', 'Archer Queen-def', 1169.9, 28);
INSERT INTO building VALUES('qeen_def29', 'Archer Queen-def', 1210.2, 29);
INSERT INTO building VALUES('qeen_def30', 'Archer Queen-def', 1250.4, 30);
INSERT INTO building VALUES('qeen_def31', 'Archer Queen-def', 1290.5, 31);
INSERT INTO building VALUES('qeen_def32', 'Archer Queen-def', 1330.5, 32);
INSERT INTO building VALUES('qeen_def33', 'Archer Queen-def', 1370.4, 33);
INSERT INTO building VALUES('qeen_def34', 'Archer Queen-def', 1410.2, 34);
INSERT INTO building VALUES('qeen_def35', 'Archer Queen-def', 1449.9, 35);
INSERT INTO building VALUES('qeen_def36', 'Archer Queen-def', 1489.5, 36);
INSERT INTO building VALUES('qeen_def37', 'Archer Queen-def', 1529, 37);
INSERT INTO building VALUES('qeen_def38', 'Archer Queen-def', 1568.4, 38);
INSERT INTO building VALUES('qeen_def39', 'Archer Queen-def', 1607.7, 39);
INSERT INTO building VALUES('qeen_def40', 'Archer Queen-def', 1646.9, 40);
INSERT INTO building VALUES('qeen_def41', 'Archer Queen-def', 1686, 41);
INSERT INTO building VALUES('qeen_def42', 'Archer Queen-def', 1725, 42);
INSERT INTO building VALUES('qeen_def43', 'Archer Queen-def', 1763.9, 43);
INSERT INTO building VALUES('qeen_def44', 'Archer Queen-def', 1802.7, 44);
INSERT INTO building VALUES('qeen_def45', 'Archer Queen-def', 1841.4, 45);
INSERT INTO building VALUES('ward_off1', 'Grand Warden-off', 100, 1);
INSERT INTO building VALUES('ward_off2', 'Grand Warden-off', 200, 2);
INSERT INTO building VALUES('ward_off3', 'Grand Warden-off', 300, 3);
INSERT INTO building VALUES('ward_off4', 'Grand Warden-off', 400, 4);
INSERT INTO building VALUES('ward_off5', 'Grand Warden-off', 500, 5);
INSERT INTO building VALUES('ward_off6', 'Grand Warden-off', 600, 6);
INSERT INTO building VALUES('ward_off7', 'Grand Warden-off', 700, 7);
INSERT INTO building VALUES('ward_off8', 'Grand Warden-off', 800, 8);
INSERT INTO building VALUES('ward_off9', 'Grand Warden-off', 900, 9);
INSERT INTO building VALUES('ward_off10', 'Grand Warden-off', 1000, 10);
INSERT INTO building VALUES('ward_off11', 'Grand Warden-off', 1100, 11);
INSERT INTO building VALUES('ward_off12', 'Grand Warden-off', 1200, 12);
INSERT INTO building VALUES('ward_off13', 'Grand Warden-off', 1300, 13);
INSERT INTO building VALUES('ward_off14', 'Grand Warden-off', 1400, 14);
INSERT INTO building VALUES('ward_off15', 'Grand Warden-off', 1500, 15);
INSERT INTO building VALUES('ward_off16', 'Grand Warden-off', 1600, 16);
INSERT INTO building VALUES('ward_off17', 'Grand Warden-off', 1700, 17);
INSERT INTO building VALUES('ward_off18', 'Grand Warden-off', 1800, 18);
INSERT INTO building VALUES('ward_off19', 'Grand Warden-off', 1900, 19);
INSERT INTO building VALUES('ward_off20', 'Grand Warden-off', 2000, 20);
INSERT INTO building VALUES('ward_def1', 'Grand Warden-def', 64, 1);
INSERT INTO building VALUES('ward_def2', 'Grand Warden-def', 127, 2);
INSERT INTO building VALUES('ward_def3', 'Grand Warden-def', 189.9, 3);
INSERT INTO building VALUES('ward_def4', 'Grand Warden-def', 252.7, 4);
INSERT INTO building VALUES('ward_def5', 'Grand Warden-def', 315.4, 5);
INSERT INTO building VALUES('ward_def6', 'Grand Warden-def', 378, 6);
INSERT INTO building VALUES('ward_def7', 'Grand Warden-def', 440.5, 7);
INSERT INTO building VALUES('ward_def8', 'Grand Warden-def', 502.9, 8);
INSERT INTO building VALUES('ward_def9', 'Grand Warden-def', 565.2, 9);
INSERT INTO building VALUES('ward_def10', 'Grand Warden-def', 627.4, 10);
INSERT INTO building VALUES('ward_def11', 'Grand Warden-def', 689.5, 11);
INSERT INTO building VALUES('ward_def12', 'Grand Warden-def', 751.5, 12);
INSERT INTO building VALUES('ward_def13', 'Grand Warden-def', 813.4, 13);
INSERT INTO building VALUES('ward_def14', 'Grand Warden-def', 875.2, 14);
INSERT INTO building VALUES('ward_def15', 'Grand Warden-def', 936.9, 15);
INSERT INTO building VALUES('ward_def16', 'Grand Warden-def', 998.5, 16);
INSERT INTO building VALUES('ward_def17', 'Grand Warden-def', 1060, 17);
INSERT INTO building VALUES('ward_def18', 'Grand Warden-def', 1121.4, 18);
INSERT INTO building VALUES('ward_def19', 'Grand Warden-def', 1182.7, 19);
INSERT INTO building VALUES('ward_def20', 'Grand Warden-def', 1243.9, 20);

#Building details max available and level
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Cannon' AND level = 0), 'validth1', 2, 2, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Cannon' AND level = 0), 'validth2', 3, 2, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Cannon' AND level = 0), 'validth3', 4, 2, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Cannon' AND level = 0), 'validth4', 5, 2, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Cannon' AND level = 0), 'validth5', 6, 3, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Cannon' AND level = 0), 'validth6', 7, 3, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Cannon' AND level = 0), 'validth7', 8, 5, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Cannon' AND level = 0), 'validth8', 10, 5, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Cannon' AND level = 0), 'validth9', 11, 5, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Cannon' AND level = 0), 'validth10', 13, 6, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Cannon' AND level = 0), 'validth11', 15, 7, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Archer Tower' AND level = 0), 'validth2', 2, 1, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Archer Tower' AND level = 0), 'validth3', 3, 1, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Archer Tower' AND level = 0), 'validth4', 4, 2, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Archer Tower' AND level = 0), 'validth5', 6, 3, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Archer Tower' AND level = 0), 'validth6', 7, 3, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Archer Tower' AND level = 0), 'validth7', 8, 4, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Archer Tower' AND level = 0), 'validth8', 10, 5, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Archer Tower' AND level = 0), 'validth9', 11, 6, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Archer Tower' AND level = 0), 'validth10', 13, 7, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Archer Tower' AND level = 0), 'validth11', 15, 8, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Mortar' AND level = 0), 'validth3', 1, 1, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Mortar' AND level = 0), 'validth4', 2, 1, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Mortar' AND level = 0), 'validth5', 3, 1, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Mortar' AND level = 0), 'validth6', 4, 2, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Mortar' AND level = 0), 'validth7', 5, 3, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Mortar' AND level = 0), 'validth8', 6, 4, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Mortar' AND level = 0), 'validth9', 7, 4, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Mortar' AND level = 0), 'validth10', 8, 4, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Mortar' AND level = 0), 'validth11', 10, 4, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Air Defense' AND level = 0), 'validth4', 2, 1, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Air Defense' AND level = 0), 'validth5', 3, 1, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Air Defense' AND level = 0), 'validth6', 4, 2, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Air Defense' AND level = 0), 'validth7', 5, 3, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Air Defense' AND level = 0), 'validth8', 6, 3, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Air Defense' AND level = 0), 'validth9', 7, 4, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Air Defense' AND level = 0), 'validth10', 8, 4, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Air Defense' AND level = 0), 'validth11', 9, 4, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Wizard Tower' AND level = 0), 'validth5', 2, 1, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Wizard Tower' AND level = 0), 'validth6', 3, 2, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Wizard Tower' AND level = 0), 'validth7', 4, 2, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Wizard Tower' AND level = 0), 'validth8', 6, 3, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Wizard Tower' AND level = 0), 'validth9', 7, 4, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Wizard Tower' AND level = 0), 'validth10', 9, 4, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Wizard Tower' AND level = 0), 'validth11', 10, 5, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Air Sweeper' AND level = 0), 'validth6', 2, 1, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Air Sweeper' AND level = 0), 'validth7', 3, 1, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Air Sweeper' AND level = 0), 'validth8', 4, 1, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Air Sweeper' AND level = 0), 'validth9', 5, 2, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Air Sweeper' AND level = 0), 'validth10', 6, 2, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Air Sweeper' AND level = 0), 'validth11', 6, 2, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Hidden Tesla' AND level = 0), 'validth7', 3, 2, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Hidden Tesla' AND level = 0), 'validth8', 6, 3, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Hidden Tesla' AND level = 0), 'validth9', 7, 4, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Hidden Tesla' AND level = 0), 'validth10', 8, 4, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Hidden Tesla' AND level = 0), 'validth11', 9, 4, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Bomb Tower' AND level = 0), 'validth8', 2, 1, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Bomb Tower' AND level = 0), 'validth9', 3, 1, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Bomb Tower' AND level = 0), 'validth10', 4, 2, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Bomb Tower' AND level = 0), 'validth11', 5, 2, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'X-Bow' AND level = 0), 'validth9', 3, 2, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'X-Bow' AND level = 0), 'validth10', 4, 3, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'X-Bow' AND level = 0), 'validth11', 5, 4, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Inferno Tower' AND level = 0), 'validth10', 3, 2, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Inferno Tower' AND level = 0), 'validth11', 5, 2, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Eagle Artillery' AND level = 0), 'validth11', 2, 1, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Walls' AND level = 0), 'validth2', 2, 25, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Walls' AND level = 0), 'validth3', 3, 50, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Walls' AND level = 0), 'validth4', 4, 75, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Walls' AND level = 0), 'validth5', 5, 100, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Walls' AND level = 0), 'validth6', 6, 125, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Walls' AND level = 0), 'validth7', 7, 175, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Walls' AND level = 0), 'validth8', 8, 225, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Walls' AND level = 0), 'validth9', 10, 250, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Walls' AND level = 0), 'validth10', 11, 275, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Walls' AND level = 0), 'validth11', 12, 300, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Bomb' AND level = 0), 'validth3', 2, 2, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Bomb' AND level = 0), 'validth4', 2, 2, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Bomb' AND level = 0), 'validth5', 3, 4, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Bomb' AND level = 0), 'validth6', 3, 4, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Bomb' AND level = 0), 'validth7', 4, 6, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Bomb' AND level = 0), 'validth8', 5, 6, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Bomb' AND level = 0), 'validth9', 6, 6, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Bomb' AND level = 0), 'validth10', 6, 6, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Bomb' AND level = 0), 'validth11', 6, 6, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Spring Trap' AND level = 0), 'validth4', 1, 2, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Spring Trap' AND level = 0), 'validth5', 1, 2, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Spring Trap' AND level = 0), 'validth6', 1, 4, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Spring Trap' AND level = 0), 'validth7', 2, 4, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Spring Trap' AND level = 0), 'validth8', 3, 6, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Spring Trap' AND level = 0), 'validth9', 4, 6, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Spring Trap' AND level = 0), 'validth10', 5, 6, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Spring Trap' AND level = 0), 'validth11', 5, 6, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Air Bomb' AND level = 0), 'validth5', 2, 2, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Air Bomb' AND level = 0), 'validth6', 2, 2, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Air Bomb' AND level = 0), 'validth7', 3, 2, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Air Bomb' AND level = 0), 'validth8', 3, 4, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Air Bomb' AND level = 0), 'validth9', 4, 4, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Air Bomb' AND level = 0), 'validth10', 4, 5, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Air Bomb' AND level = 0), 'validth11', 4, 5, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Giant Bomb' AND level = 0), 'validth6', 2, 1, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Giant Bomb' AND level = 0), 'validth7', 2, 2, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Giant Bomb' AND level = 0), 'validth8', 3, 3, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Giant Bomb' AND level = 0), 'validth9', 3, 4, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Giant Bomb' AND level = 0), 'validth10', 4, 5, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Giant Bomb' AND level = 0), 'validth11', 4, 5, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Seeking Air Mine' AND level = 0), 'validth7', 1, 1, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Seeking Air Mine' AND level = 0), 'validth8', 1, 2, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Seeking Air Mine' AND level = 0), 'validth9', 2, 4, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Seeking Air Mine' AND level = 0), 'validth10', 3, 5, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Seeking Air Mine' AND level = 0), 'validth11', 3, 5, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Skeleton Trap' AND level = 0), 'validth8', 2, 2, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Skeleton Trap' AND level = 0), 'validth9', 3, 2, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Skeleton Trap' AND level = 0), 'validth10', 3, 3, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Skeleton Trap' AND level = 0), 'validth11', 3, 3, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Gold Mine' AND level = 0), 'validth1', 2, 1, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Gold Mine' AND level = 0), 'validth2', 4, 2, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Gold Mine' AND level = 0), 'validth3', 6, 3, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Gold Mine' AND level = 0), 'validth4', 8, 4, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Gold Mine' AND level = 0), 'validth5', 10, 5, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Gold Mine' AND level = 0), 'validth6', 10, 6, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Gold Mine' AND level = 0), 'validth7', 11, 6, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Gold Mine' AND level = 0), 'validth8', 12, 6, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Gold Mine' AND level = 0), 'validth9', 12, 7, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Gold Mine' AND level = 0), 'validth10', 12, 7, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Gold Mine' AND level = 0), 'validth11', 12, 7, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Gold Storage' AND level = 0), 'validth1', 1, 1, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Gold Storage' AND level = 0), 'validth2', 3, 1, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Gold Storage' AND level = 0), 'validth3', 6, 2, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Gold Storage' AND level = 0), 'validth4', 8, 2, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Gold Storage' AND level = 0), 'validth5', 9, 2, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Gold Storage' AND level = 0), 'validth6', 10, 2, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Gold Storage' AND level = 0), 'validth7', 11, 2, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Gold Storage' AND level = 0), 'validth8', 11, 3, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Gold Storage' AND level = 0), 'validth9', 11, 4, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Gold Storage' AND level = 0), 'validth10', 11, 4, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Gold Storage' AND level = 0), 'validth11', 12, 4, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Elixir Collector' AND level = 0), 'validth1', 2, 1, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Elixir Collector' AND level = 0), 'validth2', 4, 2, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Elixir Collector' AND level = 0), 'validth3', 6, 3, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Elixir Collector' AND level = 0), 'validth4', 8, 4, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Elixir Collector' AND level = 0), 'validth5', 10, 5, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Elixir Collector' AND level = 0), 'validth6', 10, 6, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Elixir Collector' AND level = 0), 'validth7', 11, 6, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Elixir Collector' AND level = 0), 'validth8', 12, 6, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Elixir Collector' AND level = 0), 'validth9', 12, 7, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Elixir Collector' AND level = 0), 'validth10', 12, 7, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Elixir Collector' AND level = 0), 'validth11', 12, 7, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Elixir Storage' AND level = 0), 'validth1', 1, 1, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Elixir Storage' AND level = 0), 'validth2', 3, 1, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Elixir Storage' AND level = 0), 'validth3', 6, 2, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Elixir Storage' AND level = 0), 'validth4', 8, 2, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Elixir Storage' AND level = 0), 'validth5', 9, 2, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Elixir Storage' AND level = 0), 'validth6', 10, 2, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Elixir Storage' AND level = 0), 'validth7', 11, 2, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Elixir Storage' AND level = 0), 'validth8', 11, 3, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Elixir Storage' AND level = 0), 'validth9', 11, 4, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Elixir Storage' AND level = 0), 'validth10', 11, 4, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Elixir Storage' AND level = 0), 'validth11', 12, 4, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Dark Elixir Drill' AND level = 0), 'validth7', 3, 1, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Dark Elixir Drill' AND level = 0), 'validth8', 3, 2, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Dark Elixir Drill' AND level = 0), 'validth9', 6, 2, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Dark Elixir Drill' AND level = 0), 'validth10', 6, 3, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Dark Elixir Drill' AND level = 0), 'validth11', 6, 3, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Dark Elixir Storage' AND level = 0), 'validth7', 2, 1, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Dark Elixir Storage' AND level = 0), 'validth8', 4, 1, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Dark Elixir Storage' AND level = 0), 'validth9', 6, 1, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Dark Elixir Storage' AND level = 0), 'validth10', 6, 1, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Dark Elixir Storage' AND level = 0), 'validth11', 6, 1, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Clan Castle' AND level = 0), 'validth3', 1, 1, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Clan Castle' AND level = 0), 'validth4', 2, 1, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Clan Castle' AND level = 0), 'validth5', 2, 1, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Clan Castle' AND level = 0), 'validth6', 3, 1, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Clan Castle' AND level = 0), 'validth7', 3, 1, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Clan Castle' AND level = 0), 'validth8', 4, 1, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Clan Castle' AND level = 0), 'validth9', 5, 1, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Clan Castle' AND level = 0), 'validth10', 6, 1, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Clan Castle' AND level = 0), 'validth11', 7, 1, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Army Camp' AND level = 0), 'validth1', 1, 1, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Army Camp' AND level = 0), 'validth2', 2, 1, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Army Camp' AND level = 0), 'validth3', 3, 2, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Army Camp' AND level = 0), 'validth4', 4, 2, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Army Camp' AND level = 0), 'validth5', 5, 3, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Army Camp' AND level = 0), 'validth6', 6, 3, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Army Camp' AND level = 0), 'validth7', 6, 4, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Army Camp' AND level = 0), 'validth8', 6, 4, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Army Camp' AND level = 0), 'validth9', 7, 4, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Army Camp' AND level = 0), 'validth10', 8, 4, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Army Camp' AND level = 0), 'validth11', 8, 4, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Barbarian King' AND level = 0), 'validth7', 5, 1, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Barbarian King' AND level = 0), 'validth8', 10, 1, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Barbarian King' AND level = 0), 'validth9', 30, 1, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Barbarian King' AND level = 0), 'validth10', 40, 1, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Barbarian King' AND level = 0), 'validth11', 45, 1, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Archer Queen' AND level = 0), 'validth9', 30, 1, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Archer Queen' AND level = 0), 'validth10', 40, 1, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Archer Queen' AND level = 0), 'validth11', 45, 1, 0);
INSERT INTO building_detail VALUES((SELECT building_id FROM building where name = 'Grand Warden' AND level = 0), 'validth11', 20, 1, 0);
